#!/usr/bin/env python3

import discord
from discord.ext import commands

import asyncio

from typing import Optional, Dict, List

from ..helpers import BotStates
from ..handlers.exit_handling import ExitHandler

exit_handler: ExitHandler = ...

states: BotStates = ...

class DeveloperCommands:
    icon: str = ...
    def __init__(self: DeveloperCommands, database: Database):
        self.database: Database = ...
        self._last_result: Optional[str] = ...
    async def say(self: DeveloperCommands, ctx: commands.Context, *, text: str): ...
    async def kill(self: DeveloperCommands, ctx: commands.Context, wait: str = ...):
        confirm: bool = ...
        message: discord.Message = ...

        commands_running: int = ...

        s: str = ...
    async def guild_info(self: DeveloperCommands, ctx: commands.Context):
        guild: discord.Guild = ...
        embed: discord.Embed = ...
    async def sudo(
        self: DeveloperCommands,
        ctx: commands.Context,
        command: Optional[str] = ...,
        *,
        arguments: str = ...,
    ):
        new_message: discord.Message = ...
        new_ctx: commands.Context = ...
    async def eval(self: DeveloperCommands, ctx: commands.Context, *, code: str):
        environment: Dict[
            commands.Bot,
            commands.Context,
            discord.Channel,
            Union[discord.User, discord.Member],
            discord.Guild,
            discord.Message,
            str,
        ]

        code: str = ...
    async def update(self: DeveloperCommands, ctx: commands.Context):
        git_update: asyncio.subprocess.Process = ...

        stdout: bytes = ...
        stderr: bytes = ...

        error: str = ...
        output: str = ...

        result: str = ...
        result_truncated: str = ...
    async def __local_check(self: DeveloperCommands, ctx: commands.Context) -> bool: ...

def cleanup_code(content: str) -> str:
    code_languages: List[str] = ...

    content_lines: str = ...

def setup(bot: commands.Bot, database: Database): ...
