#!/usr/bin/env python3

import discord
from discord.ext import commands

import aiohttp

import datetime

from typing import Optional, Set, List, Tuple, Dict

from ..helpers import helper_functions, session_helper
from ..helpers.database_helper import Database

class GeneralCommands:
    icon: str = ...
    def __init__(self: GeneralCommands, database: Database) -> None:
        self.database: Database = ...
    async def ping(self: GeneralCommands, ctx: commands.Context, round_to: int = ...):
        latency_time: float = ...

        message: str = ...
    async def help(
        self: GeneralCommands, ctx: commands.Context, command: Optional[str] = ...
    ):
        embed: discord.Embed = ...
        name: str = ...
        description: str = ...
        icon: Optional[str] = ...
        cog_commands: Set[commands.Command] = ...

        cog_command: commands.Command = ...
        command_usage: str = ...
        header: str = ...
    async def uptime(self: GeneralCommands, ctx: commands.Context):
        current_time: datetime.datetime = ...
        running_time_delta: datetime.timedelta = ...
        running_time: str = ...

        message: str
    async def trivia(self: GeneralCommands, ctx: commands.Context):
        something_went_wrong: str = ...
        url: str = ...

        session: aiohttp.ClientSession = ...

        response: aiohttp.ClientResponse[source] = ...
        trivia: Dict = ...

        category: str = ...
        question: str = ...
        question_type: str = ...
        correct_answer: str = ...
        incorrect_answers: List[str] = ...

        answers: List[str] = ...

        formatted_answers = List[str] = ...

        unchecked_answers = List[str] = ...

        embed: discord.Embed = ...

        message: discord.Message = ...
        number_emojis: List[str] = ...

        too_slow: discord.Embed = ...

        reaction: Optional[
            Union[discord.Reaction, discord.Emoji, discord.PartialEmoji, str]
        ] = ...

        chosen_number: str = ...
        correct_number: int = ...
        correct_emoji: str = ...

        chosen_answers: List[str] = ...

def setup(bot: commands.Bot, database: Database): ...
