#!/usr/bin/env python3

import discord
from discord.ext import commands

from typing import Optional, List

loading: Optional[discord.Emoji] = ...
cancel: Optional[discord.Emoji] = ...
yes: Optional[discord.Emoji] = ...
no: Optional[discord.Emoji] = ...
cog: Optional[discord.Emoji] = ...
gear: Optional[discord.Emoji] = ...
circle_check: Optional[discord.Emoji] = ...
circle_x: Optional[discord.Emoji] = ...
radio_on: Optional[discord.Emoji] = ...
radio_off: Optional[discord.Emoji] = ...

sweat_smile: str = ...

number_emojis: List[str] = ...
number_reactions: List[Optional[discord.Emoji]] = ...

zzz_emoji: str = ...
zzz: Optional[discord.Emoji] = ...

def get_emojis(bot: commands.Bot): ...
