#!/usr/bin/env python3

import logging
import logging.handlers
import sys

def start_logging():
    log_format: logging.Formatter = ...
    logs: str = ...
    bot_log_file: str = ...

    logger: logging.Logger = ...

    stream_handler: logging.StreamHandler = ...

    bot_log_handler: logging.handlers.RotatingFileHandler = ...
