#!/usr/bin/env python3

import discord
from discord.ext import commands

from typing import List, Union

from ..helpers.database_helper import Database

class CommandErrorHandler:
    """Handles any errors the bot will throw."""

    def __init__(self: CommandErrorHandler, database: Database) -> None:
        self.database: Database = ...
    async def on_command_error(
        self: CommandErrorHandler, ctx: commands.Context, error: BaseException
    ):
        error: BaseException = ...
        command_name: str = ...

        is_owner: bool = ...

        all_command_names: List[str] = ...
        closest_command_name: str = ...
        closest_ratio: int = ...

        no_command: str = ...
        try_help_command: str = ...

        message: discord.Message = ...
        reaction: discord.Reactions = ...

        new_message: discord.Message = ...
        _: str = ...
        arguments: str = ...

        is_owner: bool = ...

def setup(bot: commands.Bot, database: Database): ...
